* Labels
cap label var id_cand "Candidate ID"
cap label var year "Election year"
cap label var dep	"Department code"
cap label var candidat	"Candidate name"
cap label var limit "Spending cap"
cap label var limit_cst "Spending cap (constant euros)"
cap label var sector_multidonor "Sector if company>1 donation"
cap label var sector_bigcompany "Sector if company>10 donations"
cap label var donor_multi_circo "Donor gave if different districts"
cap label var nb_circo_actif "# districts of the donor"
cap label var donor_multi_dep "Donor gave if different departments"
cap label var nb_dep_actif "# departments of the donor"
cap label var nb_party	"Nb parties funded by the donor"
cap label var donor_multiparty "Donor gave to more that one party"
cap label var donor_oneparty "Donor gave to one party"
cap label var donor_left "Donations only to left candidates"
cap label var donor_right "Donations only to right candidates"
cap label var donor_notideo "Donations to left and right candidates (if multiple)"
cap label var onebig "At least one Firm don. at the cap"
cap label var nb_big "\# Firm don. at the cap"
cap label var nb_local	"\# Firm don. from small donors"
cap label var nb_multiple "\# Firm don. from multiple donors"
cap label var nb_multiparty "\# Firm don. from multi-party donors"
cap label var nb_oneparty "\# Firm don. from one-party donors"
cap label var nb_left "\# Firm don. from left-wing donors"
cap label var nb_right "\# Firm don. from right-wing donors"
cap label var nb_multiside "\# Firm don. from non-ideological donors"
cap label var nb_onedep "\# Firm don. from local donors"
cap label var nb_multidep "\# Firm don. from widespread donors"
cap label var nb_onedep "\# Firm don. from local donors"
cap label var nb_multicirc "\# Firm don. from multi-district donors"
cap label var nb_onecirc "\# Firm don. from single-district donors"
cap label var cand "Candidate ID (use this one in final dataset)"
cap label var nb_election "\# elections of the candidate"
cap label var montant_donations "Total donations (euro/voter)"
cap label var dons_firms "Firm don. (euro/voter)"
cap label var dons_indiv "Indiv don. (euro/voter)"
cap label var party_contrib "Party contrib. (euro/voter)"
cap label var personal_contrib "Personal contrib. (euro/voter)"
cap label var revenues "Revenues (euro/voter)"
cap label var expenditures	"Expenditures (euro/voter)"
cap label var dons_other_sector "Firm don. from: other sectors (euro/voter)"
cap label var dons_agriculture	"Firm don. from: agriculture (euro/voter)"
cap label var dons_construction "Firm don. from: construction (euro/voter)"
cap label var dons_culture "Firm don. from: culture (euro/voter)"
cap label var dons_economy	"Firm don. from: economy (euro/voter)"
cap label var dons_environment "Firm don. from: environment (euro/voter)"
cap label var dons_foreign "Firm don. from: foreign (euro/voter)"
cap label var dons_health "Firm don. from: health (euro/voter)"
cap label var dons_industry "Firm don. from: industry (euro/voter)"
cap label var dons_justice	"Firm don. from: justice (euro/voter)"
cap label var dons_pme	"Firm don. from: retail (euro/voter)"
cap label var dons_public "Firm don. from: public (euro/voter)"
cap label var dons_sport"Firm don. from: sport (euro/voter)"
cap label var dons_unknown "Firm don. from: unknown (euro/voter)"
cap label var nb_dons "\# Firm don./voter"
cap label var don_other_sector "Firm don. from: other sectors"
cap label var don_agriculture "Firm don. from: agriculture"
cap label var don_construction	"Firm don. from: construction"
cap label var don_culture "Firm don. from: culture"
cap label var don_economy "Firm don. from: economy"
cap label var don_environment "Firm don. from: environment"
cap label var don_foreign "Firm don. from: foreign"
cap label var don_health "Firm don. from: health"
cap label var don_industry "Firm don. from: industry"
cap label var don_justice "Firm don. from: justice"
cap label var don_pme "Firm don. from: retail"
cap label var don_public "Firm don. from: public"
cap label var don_sport "Firm don. from: sport"
cap label var don_unknown "Firm don. from: unknown"
cap label var nb_other_sector "\# Firm don. from: other sectors (euro/voter)"
cap label var nb_agriculture "\# Firm don. from: agriculture (euro/voter)"
cap label var nb_construction "\# Firm don. from: construction (euro/voter)"
cap label var nb_culture "\# Firm don. from: culture (euro/voter)"
cap label var nb_economy "\# Firm don. from: economy (euro/voter)"
cap label var nb_environment "\# Firm don. from: environment (euro/voter)"
cap label var nb_foreign "\# Firm don. from: foreign (euro/voter)"
cap label var nb_health "\# Firm don. from: health (euro/voter)"
cap label var nb_industry "\# Firm don. from: industry (euro/voter)"
cap label var nb_justice "\# Firm don. from: justice (euro/voter)"
cap label var nb_pme "\# Firm don. from: retail (euro/voter)"
cap label var nb_public "\# Firm don. from: public (euro/voter)"
cap label var nb_sport	"\# Firm don. from: sport (euro/voter)"
cap label var nb_unknown "\# Firm don. from: unknown (euro/voter)"
cap label var sh_dons_other_sector "Firm don. from: other sectors (share donations)"
cap label var sh_dons_agriculture "Firm don. from: agriculture (share donations)"
cap label var sh_dons_construction "Firm don. from: construction (share donations)"
cap label var sh_dons_culture "Firm don. from: culture (share donations)"
cap label var sh_dons_economy "Firm don. from: economy (share donations)"
cap label var sh_dons_environment "Firm don. from: environment (share donations)"
cap label var sh_dons_foreign "Firm don. from: foreign (share donations)"
cap label var sh_dons_health "Firm don. from: health (share donations)"
cap label var sh_dons_industry "Firm don. from: industry (share donations)"
cap label var sh_dons_justice "Firm don. from: justice (share donations)"
cap label var sh_dons_pme "Firm don. from: retail (share donations)"
cap label var sh_dons_public "Firm don. from: public (share donations)"
cap label var sh_dons_sport "Firm don. from: sport (share donations)"
cap label var sh_dons_unknown "Firm don. from: unknown (share donations)"
cap label var sh_dons_multiparty "Share Firm don.: multi-party"
cap label var sh_dons_oneparty	"Share Firm don.: to one party"
cap label var sh_dons_multicirc "Share Firm don.: to multi-district"
cap label var sh_dons_onecirc "Share Firm don.: to one district"  
cap label var dons_local "Firm don. from: small donors (euro/voter)"
cap label var dons_multiple "Firm don. from: multiple donors (euro/voter)"
cap label var dons_multiparty "Firm don. from: multi-party donors (euro/voter)"
cap label var dons_oneparty "Firm don. from: one-party donors (euro/voter)"
cap label var dons_onecirc	"Firm don. from: single-district donors (euro/voter)"
cap label var dons_multicirc "Firm don. from: multi-district donors (euro/voter)"
cap label var dons_left "Firm don. from: left-wing donors (euro/voter)"
cap label var dons_right "Firm don. from: right-wing donors (euro/voter)"
cap label var don_local "Firm don. from: small donors"
cap label var don_multiple	"Firm don. from: multiple donors"
cap label var don_multiparty "Firm don. from: multi-party donors"
cap label var don_oneparty	"Firm don. from: one-party donors"
cap label var don_onecirc "Firm don. from: single-district donors"
cap label var don_multicirc "Firm don. from: multi-district donors"
cap label var don_left	 "Firm don. from: left-wing donors"
cap label var don_right "Firm don. from: right-wing donors"
cap label var dons_multiside "Firm don. from: non-ideological donors (euro/voter)"
cap label var std_montant_donations "Total donations"
cap label var std_dons_firms "Firm donations"
cap label var std_dons_indiv "Individual donations"
cap label var std_party_contrib "Party contributions"
cap label var std_personal_contrib "Personal contributions"
cap label var std_revenues "Total revenue"
cap label var codegeo "District code"
cap label var party	"Party"
cap label var nuance1 "Political nuance"
cap label var nuance "Political nuance"
cap label var key_candid "Key candidate for matching"
cap label var id_donation "Id donation"
cap label var  nb_donor	"\# donors"
cap label var  donor_id	"donor id"
cap label var  nb_dons_donor "Total by donor"
cap label var  local_donor "Local donor"
cap label var  sector "Sector"	
cap label var  nb_dons_circo "\# donations in district"
cap label var  nb_dons_dep "\# donations in district"
cap label var  nb_don "Number of Firm don."
cap label var atlone  "Firm don. (dummy)"
cap label var montant_total "Total amount of Firm don."
cap label var montant_total_cst	"Total amount of Firm don. (constant euros)"
cap label var total_private_donation "Total private donations"
cap label var private_donation_individuals "Private donations from individuals"
cap label var balance "Balance"
cap label var private_donation_firms "Private donations from firms"
cap label var apport_personnels_versement "Personnal contributions" 
cap label var apport_personnels_avances "Personnal contributions advanced"	
cap label var total_expenditures "Total expenditures"
cap label var total_revenues "Total revenues"
cap label var party_contribution "Party contribution"
cap label var kind_contribution "In-kind contribution"
cap label var personal_contribution	"Personal contibutions"
cap label var private_donation_indiv_cst "Private donations from individuals (constant euros)"
cap label var balance_cst "Balance (constant euros)"
cap label var private_donation_firms_cst "Private donations from firms (constant euros)"
cap label var apport_personnels_versement_cst "Personnal contributions (constant euros)" 
cap label var apport_personnels_avances_cst "Personnal contributions advanced (constant euros)"	
cap label var total_expenditures_cst "Total expenditures (constant euros)"
cap label var total_revenues_cst "Total revenues (constant euros)"
cap label var party_contribution_cst "Party contribution (constant euros)"
cap label var kind_contribution_cst "In-kind contribution (constant euros)"
cap label var other_cst "Other revenues (constant euros)"
cap label var personal_contribution_cst "Personal contibutions (constant euros)"
cap label var other_kind_cst "Other in kind revenues (constant euros) "
cap label var ln_montant_donations "Total donations (log)"
cap label var ln_dons_firms	"Firm don. (log)"
cap label var ln_dons_indiv	"Indiv don. (log)"
cap label var ln_party_contrib	"Party contrib. (log)"
cap label var ln_personal_contrib "Personal contrib. (log)"
cap label var ln_revenues "Cand.Revenues (log)"
cap label var ln_expenditures "Cand.Expenditures (log)"
cap label var ln_dons_other_sector "Firm don. from: other sectors (log)"
cap label var ln_dons_agriculture "Firm don. from: agriculture (log)"
cap label var ln_dons_construction 	"Firm don. from: construction (log)"
cap label var ln_dons_culture "Firm don. from: culture (log)"
cap label var ln_dons_economy "Firm don. from: economy (log)"
cap label var ln_dons_environment "Firm don. from: environment (log)"
cap label var ln_dons_foreign "Firm don. from: foreign (log)"
cap label var ln_dons_health "Firm don. from: health (log)"
cap label var ln_dons_industry "Firm don. from: industry (log)"
cap label var ln_dons_justice "Firm don. from: justice (log)"
cap label var ln_dons_pme "Firm don. from: retail (log)"
cap label var ln_dons_public "Firm don. from: public (log)"
cap label var ln_dons_sport	"Firm don. from: sport (log)"
cap label var ln_dons_unknown "Firm don. from: unknown (log)"
cap label var ln_dons_local	"Firm don. from: small donors (log)"
cap label var ln_dons_local_n2 "Firm don. from: small donors \leq2 (log)"
cap label var ln_dons_local_n3 "Firm don. from: small donors \leq3 (log)"
cap label var ln_dons_local_n5	"Firm don. from: small donors \leq5 (log)"
cap label var ln_dons_multiple	"Firm don. from: multiple donors (log)"
cap label var ln_dons_multiple_n2 "Firm don. from: multiple donors >2 (log)"
cap label var ln_dons_multiple_n3 "Firm don. from: multiple donors >3 (log)"
cap label var ln_dons_multiple_n5 "Firm don. from: multiple donors >5 (log)"
cap label var ln_dons_multiparty "Firm don. from: multi-party donors (log)"
cap label var ln_dons_oneparty  "Firm don. from: one-party donors (log)"
cap label var ln_dons_multidep "Firm don. from: widespread donors (log)"
cap label var ln_dons_onedep "Firm don. from: local donors (log)"
cap label var ln_dons_onecirc "Firm don. from: single-district donors (log)"
cap label var ln_dons_multicirc	"Firm don. from: multi-district donors (log)"
cap label var ln_dons_left	"Firm don. from: left-wing donors (log)"
cap label var ln_dons_right	"Firm don. from: right-wing donors (log)"
cap label var ln_dons_other	"Firm don. from: donors to independents (log)"
cap label var ln_dons_multiside	 "Firm don. from: non-ideological donors (log)"
cap label var sh_dons_firms	 "Firm don. (share)"
cap label var sh_dons_indiv	"Indiv don. (share)"
cap label var sh_party_contrib "Party contrib. (share)"
cap label var sh_personal_contrib "Personal contrib. (share)"
cap var sh_dons_other_sector "Firm don. from: other sectors (share)"
cap var sh_dons_agriculture	"Firm don. from: agriculture (share)"
cap var sh_dons_construction "Firm don. from: construction (share)"
cap var sh_dons_culture	"Firm don. from: culture (share)"
cap var sh_dons_economy	"Firm don. from: economy (share)"
cap var sh_dons_environment "Firm don. from: environment (share)"
cap var sh_dons_foreign	"Firm don. from: foreign (share)"
cap var sh_dons_health	"Firm don. from: health (share)"
cap var sh_dons_industry "Firm don. from: industry (share)"
cap var sh_dons_justice	 "Firm don. from: justice (share)"
cap var sh_dons_pme	 "Firm don. from: retail (share)"
cap var sh_dons_public "Firm don. from: public (share)"
cap var sh_dons_sport "Firm don. from: sport (share)"
cap var sh_dons_unknown "Firm don. from: unknown (share)"
cap label var atl_other_sector "Firm don. from: other sector (dummy)"
cap label var atl_agriculture "Firm don. from: agriculture (dummy)"
cap label var atl_construction "Firm don. from: construction (dummy)"
cap label var atl_culture "Firm don. from: culture (dummy)"
cap label var atl_economy "Firm don. from: economy (dummy)"
cap label var atl_environment "Firm don. from: environment (dummy)"
cap label var atl_foreign "Firm don. from: foreign (dummy)"
cap label var atl_health "Firm don. from: health (dummy)"
cap label var atl_industry "Firm don. from: industry (dummy)"
cap label var atl_justice "Firm don. from: justice (dummy)"
cap label var atl_pme	 "Firm don. from: retail (dummy)"
cap label var atl_public "Firm don. from: public (dummy)"
cap label var atl_sport	"Firm don. from: sport (dummy)"
cap label var atl_unknown "Firm don. from: unknown (dummy)"
cap label var std_dons_other_sector "Firm don. from: other sectors"
cap label var std_dons_agriculture "Firm don. from: agriculture"
cap label var std_dons_construction "Firm don. from: construction"
cap label var std_dons_culture "Firm don. from: culture"
cap label var std_dons_economy "Firm don. from: economy"
cap label var std_dons_environment "Firm don. from: environment"
cap label var std_dons_foreign "Firm don. from: foreign"
cap label var std_dons_health "Firm don. from: health"
cap label var std_dons_industry "Firm don. from: industry"
cap label var std_dons_justice "Firm don. from: justice"
cap label var std_dons_pme "Firm don. from: retail"
cap label var std_dons_public "Firm don. from: public"
cap label var std_dons_sport "Firm don. from: sport"
cap label var std_dons_unknown "Firm don. from: unknown"

cap label var don_other_sector_cst "Firm don. from: other sectors (constant euros)"
cap label var don_agriculture_cst "Firm don. from: agriculture (constant euros)"
cap label var don_construction_cst "Firm don. from: construction (constant euros)"
cap label var don_culture_cst "Firm don. from: culture (constant euros)"
cap label var don_economy_cst  "Firm don. from: economy (constant euros)"
cap label var don_environment_cst "Firm don. from: environment (constant euros)"
cap label var don_foreign_cst  "Firm don. from: foreign (constant euros)"
cap label var don_health_cst "Firm don. from: health (constant euros)"
cap label var don_industry_cst  "Firm don. from: industry (constant euros)"
cap label var don_justice_cst "Firm don. from: justice (constant euros)"
cap label var don_pme_cst "Firm don. from: retail (constant euros)"
cap label var don_public_cst  "Firm don. from: public (constant euros)"
cap label var don_sport_cst	"Firm don. from: sport (constant euros)"
cap label var don_unknown_cst "Firm don. from: unknown (constant euros)"
cap label var std_dons_local "Firm don. from: small donors"
cap label var std_dons_multiple	 "Firm don. from: multiple donors"
cap label var std_dons_multiparty "Firm don. from: multi-party donors"
cap label var std_dons_oneparty "Firm don. from: one-party donors"
cap label var std_dons_multidep "Firm don. from: widespread donors"
cap label var std_dons_onedep "Firm don. from: local donors"
cap label var std_dons_onecirc "Firm don. from: single-district donors"
cap label var std_dons_multicirc "Firm don. from: multi-district donors"
cap label var std_dons_left	"Firm don. from: left-wing donors"
cap label var std_dons_right "Firm don. from: right-wing donors"
cap label var std_dons_multiside "Firm don. from: non-ideological donors"
cap label var don_local_cst	"Firm don. from: small donors (constant euros)"
cap label var don_multiple_cst "Firm don. from: multiple donors (constant euros)"
cap label var don_multiparty_cst "Firm don. from: multi-party donors (constant euros)"
cap label var don_oneparty_cst  "Firm don. from: one-party donors (constant euros)"
cap label var don_onecirc_cst "Firm don. from: single-district donors (constant euros)"
cap label var don_multicirc_cst  "Firm don. from: multi-district donors (constant euros)"
cap label var total_recettes "Total revenue (1988)"
cap label var dons_cheques_avec_recu "Donation by check (1988)"
cap label var dons_cheques_sans_recu "Donation by check without receipt (1988)"
cap label var dons_especes	"Donation in cash (1988)"
cap label var contribution_parti_politique	"Contribution to party (1988)"
cap label var dons_a_recevoir "Donations (1988)"
cap label var contributions	"Contributions (1988)"
cap label var emprunt_contractes_candidate "Loans (1988)"
cap label var avance_parti_politique "Advance by party (1988)"
cap label var prets_avances_fournisseurs "Advance by supplier (1988)"
cap label var dettes_candidat "Debt (1988)"
cap label var contribution_du_candidat 	"Candidate contribution (1988)"
cap label var produits_activites_annexes "Other activities (1988)"
cap label var avance_pp_de_trop	"Advance by party in surplus (1988)"
cap label var elec_margin "Election margin"
foreach i in 1988 1993 1997 {
cap label var id_`i' "Cand id in `i'"
}
foreach i in 1 2 {
cap label var ins_l`i'	"Registered voters round `i'"
cap label var  vot_l`i'	"Voters round `i'"
cap label var exp_l`i'	"\Votes round `i'"
cap label var voix_l`i'	"Registered voters round `i'"
cap label var voixexp_l`i' "Expressed votes round `i'" 	
cap label var perc_voix_ins`i' "%Votes/registered round `i'"
}
foreach item in 1993 {
cap label var total_expenditures_cst`item' "`item'"
cap label var total_revenues_cst`item' "`item'"
cap label var sh_dons_firms`item' "`item'"
cap	label var sh_dons_indiv`item' "`item'"
cap	label var sh_personal_contrib`item' "`item'"
cap	label var sh_party_contrib`item' "`item'"
}			
foreach item in 1997 {
cap	label var total_expenditures_cst`item' "`item' "
cap	label var total_revenues_cst`item' "`item'"
cap	label var sh_dons_firms`item' "`item' "
cap	label var sh_dons_indiv`item' "`item' "
cap	label var sh_personal_contrib`item' "`item' "
cap	label var sh_party_contrib`item' "`item' "
}	
	
foreach year in 1968 1975 1982 1990 1999 2008 2013 {
cap label var pasdedip`year' "No diploma in `year'"
cap label var CAP_BEP`year' "CAP-BEP in `year'"
cap label var bac`year' "High school degree in `year'"
cap label var sup`year'  "Higher education in `year'"
cap label var agri`year' "Agriculture in `year'"
cap label var inde`year'  "Independent workers in `year'"
cap label var cadre`year' "White-collar workers in `year'"
cap label var interm`year' "Intermediary workers in `year'"
cap label var employ`year' "Employees in `year'"
cap label var ouvr`year' "Blue-collar worker in `year'"
cap label var pop_0_14`year' "0-14 years old in `year'"
cap label var pop_15_24`year' "15-24 years old in `year'"
cap label var pop_0_24`year' "0-24 years old in `year'"
cap label var pop_25_34`year' "25-34 years old in `year'"	
cap label var pop_35_44`year' "35-44 years old in `year'"
cap label var pop_45_54`year' "45-54 years old in `year'"
cap label var pop_25_54`year' "25-54 years old in `year'"
cap label var pop_55_64`year' "55-64 years old in `year'"
cap label var pop_65_plus`year'"65+ years old in `year'"
cap label var pop_15_plus`year' "15+ years old in `year'"
cap label var population`year' "Population in `year'"
}
cap label var DADS_nbworker	"Number of employees"
cap label var DADS_nbestab "Number of firms"
cap label var DADS_sumwage	"Total payroll (in thousand euros)"
cap label var DADS_share_top1 "\% employees in top 1\%"		
foreach year in "" "1993" "1997" {
cap label var DADS_nbworker`year'  "Number of employees `year'"
cap label var DADS_nbestab`year' "Number of firms `year'"
cap label var DADS_sumwage`year' "Total payroll (in thousand euros) `year'"
cap label var DADS_share_top1`year'	"\% employees in top 1\% `year'"		
}
cap label var CC_investissement	"District municipalities investment expenses in"
cap label var CC_produits_fonctio "District municipalities revenues"
cap label var CC_charges_fonctio "District municipalities operating expenses"
cap label var CC_impots_locaux "District municipalities local taxes"
foreach year in "" "1993_cst" "1997_cst" {
cap label var CC_investissement`year'	"District municipalities investment expenses in `year'"
cap label var CC_produits_fonctio`year'	"District municipalities revenues `year'"
cap label var CC_charges_fonctio`year'	"District municipalities operating expenses `year'"
cap label var CC_impots_locaux`year'	"District municipalities local taxes 	`year'"
}
cap label var  cheflieudep "Department capital in the district"
cap label var  cheflieureg "Region capital in the district"
cap label var  surface 	"District area"
cap label var  nb_villes "\# Municipalities in the district"
cap label var  pure_urban "Urban district"
cap label var  pure_rural "Rural district"
cap label var candidat_prenom_nom "Candidate name"
cap label var female "Female"
cap label var rerun "Re-run"
cap label var Dincumbent "Incumbent"
cap label var mayor "Mayor"
cap label var other_mandate	"Other mandates"
cap label var std_cheflieudep "District seat"
cap label var std_nb_villes "Nb municipalities"
cap label var std_DADS_share_top1 "% employees top 1%"
cap label var std_DADS_nbworker "Av. nb employees"
cap label var std_DADS_nbestab	"Number of firms"
cap label var std_DADS_sumwage "Total payroll"
cap label var std_CC_charges_fonctio "Municipal expenditures"
cap label var std_pasdedip1990	"% No diploma"
cap label var std_sup1990 "% Higher education"
cap label var std_agri1990 "% Agriculture"
cap label var std_ouvr1990 "% Blue-collar worker"
cap label var std_pop_65_plus1990 "% 65+ years old"
cap label var std_pop_15_241990	"% 15-24 years old"
cap label var std_inscrits1	"Registered voters"
cap label var std_elec_margin_c_88	"Election margin in 1988"
cap label var std_limit_cst	"Spending limit"
cap label var std_change_limit_cst "Change in spending limit"
cap label var secround_circo_c_88 "No runoff in 1988"
cap label label var dons_firms "Firm donations"
cap label def atlone_l ///
0 "No firm donations in 1993" ///
1 "Firm donations in 1993"
cap label val atl_ atlone_l
cap label var dons_firms_FN  "Far-right*Firm don."
cap label var dons_firms_UMP  "Right*Firm don."
cap label var dons_firms_PS "Socialist*Firm don."
cap label var dons_firms_PC "Communist*Firm don."
cap label var dons_firms_Verts "Green*Firm don."
cap label var dons_firms_other "Other*Firm don."
cap label var small_donor  "Small donor (\%)"
cap label var morethanone "Multiple donor (\%)"  
cap label var local "Single-district donor (\%)"
cap label var multipledonor "Multi-district donor (\%)"
cap label var donor_oneparty "Single-party donor (\%)"
cap label var donor_multiparty "Multi-party donor (\%)" 
cap label var I_female "Firm don.*Female"
cap label var I_rerun  "Firm don.*Re-run"
cap label var I_Dincumbent "Firm don.*Incumbent"
cap label var I_mayor "Firm don.*Mayor"
cap label var I_other_mandate "Firm don.*Other mandates"
cap label var std_dons_firms_FN "Far-right*Firm don."
cap label var std_dons_firms_UMP "Right*Firm don."
cap label var std_dons_firms_PS "Socialist*Firm don."
cap label var std_dons_firms_PC "Communist*Firm don."
cap label var std_dons_firms_Verts "Green*Firm don."
cap label var std_dons_firms_other "Other*Firm don."
cap label var score_noloc_sr1 "Left-right score without local references"
cap label var mean_similarity_nuanc "Mean similarity to other candidates in same party"
cap label var mean_originality_nuanc "Mean originality relative to other candidates in same party"
cap label var index_originality	"Originality index"
cap label var sh_self1 "Share of references to self"
cap label var deb_high1_sh_nat  "Share of national references in high visibility debates"
cap label var deb_high1_sh_local "Share of local references in high visibility debates"
cap label var deb_high0_sh_nat	"Share of national references in low visibility debates"
cap label var deb_high0_sh_local "Share of local references in low visibility debates"
cap label var deb_sh_nat "Share of national references in debates"
cap label var deb_sh_local	"Share of local references in high visibility debates"
cap label var qu_sh_nat	"Share of national references in written questions"
cap label var qu_sh_local "Share of local references in written questions"
cap label var sh_nat_party1	"Share of party-specific national references"
cap label var sh_nat1 "Share of national references"
cap label var sh_local1	"Share of local references"
cap label var nb_deb_high1_total "Number of interventions in high visibility debates"
cap label var nb_deb_high0_total "Number of interventions in low visibility debates"
cap label var nb_deb_total "Number of interventions in debates"
cap label var deb_homeland2_prob "Prevalence of homeland issues in debates"
cap label var deb_foreign2_prob	"Prevalence of foreign issues in debates"
cap label var deb_economy2_prob "Prevalence of economic issues in debates"
cap label var deb_social2_prob "Prevalence of social issues in debates"
cap label var homeland2_prob1 "Prevalence of homeland and administration"
cap label var foreign2_prob1 "Prevalence of foreign issues"
cap label var economy2_prob1 "Prevalence of economic issues"
cap label var social2_prob1	"Prevalence of social issues"
cap label var agriculture_prob1	"Prevalence of agriculture"
cap label var culture_prob1	"Prevalence of culture"
cap label var construction_prob1 "Prevalence of construction and amenities"
cap label var defense_prob1	"Prevalence of defense"
cap label var economy_prob1	"Prevalence of economic issues"
cap label var education_prob1	"Prevalence of education"
cap label var employment_prob1	"Prevalence of employment"
cap label var environment_prob1	"Prevalence of environmental issues"
cap label var europe_prob1	"Prevalence of european issues"
cap label var foreign_prob1	"Prevalence of foreign issues"
cap label var health_prob1	"Prevalence of health issues"
cap label var industry_prob1  "Prevalence of industry"
cap label var interior_prob1 "Prevalence of homeland issues"
cap label var justice_prob1	"Prevalence of justice"
cap label var pme_prob1	"Prevalence of retail"
cap label var public_prob1	"Prevalence of public administration"
cap label var sport_prob1 "Prevalence of sport"
cap label var nb_qu_total "Total number of written questions"
cap label var qu_homeland2_prob	"Prevalence of homeland issues in written questions"
cap label var qu_foreign2_prob "Prevalence of foreign issues in written questions"
cap label var qu_economy2_prob	"Prevalence of economic issues in written questions"
cap label var qu_social2_prob "Prevalence of social issues in written questions"
cap label var abs_loading1	"Mean absolute word loading"
cap label var text_size_sr1	"Number of words"
cap label var score_sr1	"Left-right score"
cap label var ratio_local1	"Local index"
cap label var ratio_local1_2 "Local index (constant 1000)"
cap label var ratio_local1_3 "Local index (constant 0.001)"
cap label var ratio_local1_5 "Local index (ratio)"
cap label var ratio_local_party1 "Local index with party-specific references"
cap label var qu_ratio_local "Local index in written questions"
cap label var deb_ratio_local "Local index in debate interventions"
cap label var deb_high0_ratio_local	"Local index in debate interventions with low visibility"
cap label var deb_high1_ratio_local	"Local index in debate interventions with high visibility"
cap label var concen_topic "Concentration of topics"
cap label var abs_score_sr1	"Extremeness (absolute left-right score)"
cap label var abs_score_noloc_sr1 "Extremeness without local references"
cap label var ratio_local1_std "Local index"
cap label var ratio_local1_2_std "Local index (constant 1000)"
cap label var ratio_local1_3_std "Local index (constant 0.001)"
cap label var ratio_local1_5_std "Local index (ratio)"
cap label var ratio_local_party1_std "Local index with party-specific national references"
cap label var qu_ratio_local_std "Local index in written questions"
cap label var deb_ratio_local_std "Local index in debate interventions"
cap label var deb_high0_ratio_local_std	"Local index in debate interventions with low visibility"
cap label var deb_high1_ratio_local_std	"Local index in debate interventions with high visibility"
cap label var voix1 "Number of votes"
cap label var perc_voix_exp1 "%Votes/Exp"
cap label var conseiller_departemental "Member of Departmental council"
cap label var senateur "Senator"
cap label var depute_europeen "Member of European council"
cap label var bigparty "Party (among main ones)"
cap label var id_party "Party ID"
cap label var mainparty "Main party dummy"
cap label var nicheparty "Niche party dummy"
cap label var otherparty "Other party dummy"
cap label var secround_circo "Runoff in district"
cap label var score_winner "Winner vote share"
cap label var winner "Winner dummy"
cap label var run_88 "Run in 1988"
cap label var run_93 "Run in 1993"
cap label var run_97 "Run in 1997"
cap label var rerun_select "Candidate runs in next election"
cap label var party_select "Party runs in next election"
cap label var ratio_local1_partydep_8893 "Trend in local index at party*department level between 1988 and 1993"
cap label var ratio_local1_partydep_8188 "Trend in local index at party*department level between 1981 and 1988"
cap label var ratio_local1_partydep_7881 "Trend in local index at party*department level between 1978 and 1981"
cap label var ratio_local1_partydep_7378 "Trend in local index at party*department level between 1973 and 1978"
cap label var ratio_local1_partydep_6873 "Trend in local index at party*department level between 1968 and 1973"
cap label var ratio_local1_partydep_6768 "Trend in local index at party*department level between 1967 and 1968"
cap label var c_female "Share of female candidates in district"
cap label var c_rerun "Share of re-runners in district"
cap label var c_Dincumbent "Share of incumbents in district"
cap label var c_mayor "Share of mayors in district"
cap label var c_other_mandate "Share of candidates w/ other mandates in district"
cap label var elec_margin_c_88 "Election margin in 1988"
cap label var score_sr1_c_88 "Mean Left-right score in district in 1988"
cap label var score_sr1_p_88 "Mean Left-right score at party*district level in 1988"
cap label var score_sr1_i_88 "Left-right score in 1988"
cap label var abs_score_sr1_p_88 "Mean Extremeness at party*district level in 1988"
cap label var abs_score_sr1_i_88 "Extremeness in 1988"
cap label var ratio_local1_p_88 "Mean local index at party*district level in 1988"
cap label var ratio_local1_i_88 "Local index in 1988"
cap label var sh_local1_p_88 "Mean share of local references at party*district level in 1988"
cap label var sh_local1_i_88 "Share of local references in 1988"
cap label var sh_nat1_p_88 "Mean share of national references at party*district level in 1988"
cap label var sh_nat1_i_88 "Share of national references in 1988"
cap label var sh_self1_p_88 "Mean share of references to self at party*district level in 1988"
cap label var sh_self1_i_88 "Share of references to self in 1988"
cap label var index_originality_p_88 "Mean originality index at party*district level in 1988"
cap label var index_originality_i_88 "Originality index in 1988"
cap label var change_limit_cst "Change in spending cap (constant euros)"
foreach x in "93" "97"{
cap label var limit_cst_`x' "Spending cap in 19`x' (constant euros)"
cap label var cheflieudep_c_`x'	"Department capital in the district in 19`x'"
cap label var nb_villes_c_`x' 	"Number of municipalities in district in 19`x'"
cap label var DADS_nbworker_c_`x' "Mean number of employees in district in 19`x'"
cap label var DADS_nbestab_c_`x' "Mean number of firms in district in 19`x'"
cap label var DADS_sumwage_c_`x' "Total payroll (in thousand euros) in district in 19`x'"
cap label var DADS_share_top1_c_`x' "\% employees in top 1\% in district in 19`x'"
cap label var CC_produits_fonctio_c_`x'	"District municipalities revenues in district in 19`x'"
cap label var CC_charges_fonctio_c_`x' "District municipalities operating expenses in district in 19`x'"
cap label var pasdedip1990_c_`x' "No diploma in district in 19`x'"
cap label var sup1990_c_`x'	"Higher education in district in 19`x'"
cap label var agri1990_c_`x' "Agriculture in district in 19`x'"
cap label var ouvr1990_c_`x' "Blue-collar worker in district in 19`x'"
cap label var pop_15_241990_c_`x' "15-24 years old in district in 19`x'"
cap label var pop_65_plus1990_c_`x'	"65+ years old in district in 19`x'"
cap label var inscrits1_c_`x' "Registered voters in district in 19`x'"
cap label var limit_cst_c_`x' "Spending cap in 19`x' (constant euros)"
cap label var female_p_`x' "Share of female candidates at party*district level in 19`x'"
cap label var female_i_`x' "Female candidate in 19`x'"
cap label var rerun_p_`x' "Share of rerunners at party*district level in 19`x'"
cap label var rerun_i_`x' "Re-runner in 19`x'"
cap label var Dincumbent_p_`x' "Share of incumbents at party*district level in 19`x'"
cap label var Dincumbent_i_`x' "Incumbent in 19`x'"
cap label var mayor_p_`x' "Share of mayors at party*district level in 19`x'"
cap label var mayor_i_`x' "Mayor in 19`x'"
cap label var other_mandate_p_`x' "Share of candidates with other mandates at party*district level in 19`x'"
cap label var other_mandate_i_`x' "Other mandates in 19`x'"
}
cap label var female_c_88 "Share of female candidates in district in 1988"
cap label var Dincumbent_c_88 "Share of incumbents in district in 1988"
cap label var female_p_88 "Share of female candidates at party*district level in 1988"
cap label var female_i_88 "Female candidate in 1988"
cap label var Dincumbent_p_88 "Share of incumbents at party*district level in 1988"
cap label var Dincumbent_i_88 "Incumbent in 1988"
foreach x in "88" "93" "97"{
cap label var dons_firms_`x' "Firm donations in 19`x' (euros/voter)"
cap label var dons_indiv_`x' "Individual donations in 19`x' (euros/voter)"
cap label var personal_contrib_`x' "Personal contributions in 19`x' (euros/voter)"
cap label var party_contrib_`x' "Party contributions in 19`x' (euros/voter)"
}
cap label var sample_rest "Sample of candidates with both aggregate and detailed amounts of donations defined"
cap label var sample_did "Sample for Diff-in-diff analysis"
cap label var revenues_main "Total revenues with 4 main sources (euros/voter)"
cap label var sh_dons_indiv_main "Share of individual donations in total revenues with 4 main sources (euros/voter)"
cap label var sh_dons_firms_main "Share of firm donations in total revenues with 4 main sources (euros/voter)"
cap label var sh_party_contrib_main "Share of party contributions in total revenues with 4 main sources (euros/voter)"
cap label var sh_personal_contrib_main "Share of personal contributions in total revenues with 4 main sources (euros/voter)"
cap label var dons_firms_20p "First quintile of firm donations in 1993"
cap label var dons_firms_40p "Second quintile of firm donations in 1993"
cap label var dons_firms_60p "Third quintile of firm donations in 1993"
cap label var dons_firms_80p "Fourth quintile of firm donations in 1993"
cap label var dons_firms_100p "Fifth quintile of firm donations in 1993"
forval i=0/18{
cap label var nb_party`i' "Number of candidates from party ID `i' in district"
}